### ISSUE TITLE
The appendix section number is wrong.

### ISSUE THREAD

**Issue by diguage** [owenh000/asciidoctor-multipage#37] opened 2022-07-21 13:06 UTC
```
= Example Manual^Alpha^
Doc Writer <doc.writer@example.org>
2014-09-09
:icons: font
:source-highlighter: rouge
:rouge-style: monokai
:stylesdir: assets/styles/
:linkcss:

This is a user manual for an example project.

:sectnums:

[#introduction]
== Introduction

This project does something.
We just haven't decided what that is yet.


[#source-code]
[appendix]
== Source `Code` Example

[source,java]
.Java code from project
----
package com.diguage;

/**
 * @author D瓜哥 · https://www.diguage.com/
 */
public class Main {
    public static void main(String[] args)
        System.out.println("Hello, world");
    }
}
----

This page was built by the following command:

 $ mvn
```

![image](https://user-images.githubusercontent.com/2121467/180220691-f34e6382-d2d4-4f2a-9b82-2bdd42b4d4df.png)

![image](https://user-images.githubusercontent.com/2121467/180220802-df5aa72f-ba98-4a4d-9e04-0c7e73deafb1.png)

**Comment by owenh000** [comment] 2022-07-27 00:34
Hi @diguage, thanks for the report. Your example does not actually have the Table of Contents enabled, but I have confirmed the bug with the example below:

```adoc
= Example Manual
Doc Writer <doc.writer@example.org>
2014-09-09
:toc: left
:sectnums:

This is a user manual for an example project.

[#introduction]
== Introduction

This project does something.

[#source-code]
[appendix]
== Source Code Example

This is appendix content.
```

Generated with:

```console
$ bundler exec asciidoctor -r asciidoctor-multipage -b multipage_html5 -D test/out test.adoc
```

**Comment by diguage** [comment] 2022-07-27 07:14
> Hi @diguage, thanks for the report. Your example does not actually have the Table of Contents enabled, but I have confirmed the bug with the example below
@owenh000 Sorry. The `:toc: left` parameter was set by Maven, not in the document. 😄😄

**Comment by owenh000** [comment] 2022-07-27 20:12
> @owenh000 Sorry. The `:toc: left` parameter was set by Maven, not in the document. :smile::smile:

No problem! I just wanted to have a clear test case without the external dependency.

**Comment by owenh000** [comment] 2022-07-27 20:15
This issue is actually a duplicate of issue #33, so I'm closing this one in favor of it.

**Closed by owenh000** 2022-07-27 20:15 UTC
Labels: bug
